config/routes.rb
require 'api_version'

BananaPodcast::Application.routes.draw do

  scope defaults: { format: 'json' } do
    scope module: :v1, constraints: ApiVersion.new('v1') do
      resources :zombies
    end

    scope module: :v2, constraints: ApiVersion.new('v2', true) do
      resources :zombies
    end
  end

end

app/models/episode.rb
class Episode < ActiveRecord::Base
  validates :title, presence: true, length: { minimum: 10 }
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :set_auth_token

  private

    def set_auth_token
      return if auth_token.present?
      self.auth_token = generate_auth_token
    end

    def generate_auth_token
      loop do
        token = SecureRandom.hex
        break token unless self.class.exists?(auth_token: token)
      end
    end
end

app/models/zombie.rb
class Zombie < ActiveRecord::Base
  def bananas
    puts RUBY_DESCRIPTION
  end
end

app/controllers/api/zombies_controller.rb
class API::ZombiesController < ApplicationController
  def index
    zombies = Zombie.all # remember, starting in Rails 4 this returns a chainable scope
    if weapon = params[:weapon]
      zombies = zombies.where(weapon: weapon)
    end
    render json: zombies, status: 200
  end

  def show
    zombie = Zombie.find(params[:id])
    render json: zombie, status: 200
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  #protect_from_forgery with: :exception
end

app/controllers/episodes_controller.rb
class EpisodesController < ApplicationController

  def index
    @episodes = Episode.all
    respond_to do |format|
      format.json { render json: @episodes, status: 200 }
      format.apocalypse
    end
  end

  def create
    episode = Episode.new(episode_params)

    respond_to do |format|
      if episode.save
        format.json { render json: episode, status: :created, location: episode }
        format.apocalypse { render json: params, status: :created }
      else
        format.json { render json: episode.errors, status: :unprocessable_entity }
        format.apocalypse { render text: 'booo', layout: false }
      end
    end
  end

  def update
    episode = Episode.find(params[:id])
    respond_to do |format|
      if episode.update(episode_params)
        format.json { render json: episode, status: 200 }
      else
        format.json { render json: episode.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    episode = Episode.find(params[:id])
    episode.destroy!
    #render nothing: true, status: 204 # :no_content
    # or
    head :no_content
  end

  private

    def episode_params
      params.require(:episode).permit(:title, :description)
    end
end

app/controllers/v1/version_controller.rb
module V1
  class VersionController < ApplicationController
    abstract!

    before_action :set_api_version

    def set_api_version
      @api_version = 'One'
    end
  end
end

app/controllers/v1/zombies_controller.rb
module V1
  class ZombiesController < VersionController
    def index
      render text: "#{@remote_ip} Version #{@api_version}!"
    end
  end
end

app/controllers/v2/version_controller.rb
module V2
  class VersionController < ApplicationController
    abstract!

    before_action :set_api_version

    def set_api_version
      @api_version = 'Two'
    end
  end
end

app/controllers/v2/zombies_controller.rb
module V2
  class ZombiesController < VersionController
    def index
      render text: "#{@remote_ip} Version #{@api_version}!"
    end
  end
end

app/controllers/zombies_controller.rb
class ZombiesController < ApplicationController
  before_action :set_locale_with_gem, only: :index
  before_action :set_locale_with_no_gem, only: :show

  def set_locale_with_gem
    I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
  end
  protected :set_locale_with_gem

  def set_locale_with_no_gem
    I18n.locale = request.headers['Accept-Language']
  end
  protected :set_locale_with_no_gem

  # GET /zombies
  # GET /zombies.json
  def index
    @zombies = Zombie.all
    respond_to do |format|
      format.json
      format.xml { render xml: @zombies }
    end
  end

  # GET /zombies/1
  # GET /zombies/1.json
  def show
    @zombie = Zombie.first
    respond_to do |format|
      format.json
      format.xml
    end
  end

  # GET /zombies/new
  def new
    @zombie = Zombie.new
  end

  # GET /zombies/1/edit
  def edit
  end

  # POST /zombies
  # POST /zombies.json
  def create
    @zombie = Zombie.new(zombie_params)

    respond_to do |format|
      if @zombie.save
        format.html { redirect_to @zombie, notice: 'Zombie was successfully created.' }
        format.json { render action: 'show', status: :created, location: @zombie }
      else
        format.html { render action: 'new' }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /zombies/1
  # PATCH/PUT /zombies/1.json
  def update
    respond_to do |format|
      if @zombie.update(zombie_params)
        format.html { redirect_to @zombie, notice: 'Zombie was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @zombie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /zombies/1
  # DELETE /zombies/1.json
  def destroy
    @zombie.destroy
    respond_to do |format|
      format.html { redirect_to zombies_url }
      format.json { head :no_content }
    end
  end

  private
    # Never trust parameters from the scary internet, only allow the white list through.
    def zombie_params
      params.require(:zombie).permit(:name, :age)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/episodes_helper.rb
module EpisodesHelper
end

app/helpers/zombies_helper.rb
module ZombiesHelper
end

app/views/episodes/_form.html.erb
<%= form_for(@episode) do |f| %>
  <% if @episode.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@episode.errors.count, "error") %> prohibited this episode from being saved:</h2>

      <ul>
      <% @episode.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/episodes/edit.html.erb
<h1>Editing episode</h1>

<%= render 'form' %>

<%= link_to 'Show', @episode %> |
<%= link_to 'Back', episodes_path %>

app/views/episodes/index.html.erb
<h1>Listing episodes</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @episodes.each do |episode| %>
      <tr>
        <td><%= episode.title %></td>
        <td><%= episode.description %></td>
        <td><%= link_to 'Show', episode %></td>
        <td><%= link_to 'Edit', edit_episode_path(episode) %></td>
        <td><%= link_to 'Destroy', episode, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Episode', new_episode_path %>

app/views/episodes/new.html.erb
<h1>New episode</h1>

<%= render 'form' %>

<%= link_to 'Back', episodes_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BananaPodcast</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/zombies/_form.html.erb
<%= form_for(@zombie) do |f| %>
  <% if @zombie.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@zombie.errors.count, "error") %> prohibited this zombie from being saved:</h2>

      <ul>
      <% @zombie.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/zombies/edit.html.erb
<h1>Editing zombie</h1>

<%= render 'form' %>

<%= link_to 'Show', @zombie %> |
<%= link_to 'Back', zombies_path %>

app/views/zombies/index.html.erb
<h1>Listing zombies</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @zombies.each do |zombie| %>
      <tr>
        <td><%= zombie.name %></td>
        <td><%= zombie.age %></td>
        <td><%= link_to 'Show', zombie %></td>
        <td><%= link_to 'Edit', edit_zombie_path(zombie) %></td>
        <td><%= link_to 'Destroy', zombie, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Zombie', new_zombie_path %>

app/views/zombies/new.html.erb
<h1>New zombie</h1>

<%= render 'form' %>

<%= link_to 'Back', zombies_path %>

app/views/zombies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @zombie.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @zombie.age %>
</p>

<%= link_to 'Edit', edit_zombie_path(@zombie) %> |
<%= link_to 'Back', zombies_path %>